print("Ingresa Nombre")
nombre= input()
nombre2=input("Ingesa tu Nombre ")
edad=input("Ingresa tu Edad ")
numero1=input("Ingresar Numero1 ")
numero2=input("Ingresar Numero2 ")
print("Tu nombre es:" + nombre)
print("Tu Nombre es: "+nombre2)
print("Tu edad es: "+ edad)
print(int(numero1)+int(numero2))